wandb_version: 1

activation_dropout:
  desc: null
  value: 0.1
activation_function:
  desc: null
  value: gelu
add_bias_logits:
  desc: null
  value: false
add_final_layer_norm:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - EBartModel
attention_dropout:
  desc: null
  value: 0.1
bos_token_id:
  desc: null
  value: 0
classif_dropout:
  desc: null
  value: 0.1
classifier_dropout:
  desc: null
  value: 0.0
d_model:
  desc: null
  value: 1024
decoder_attention_heads:
  desc: null
  value: 16
decoder_ffn_dim:
  desc: null
  value: 4096
decoder_layerdrop:
  desc: null
  value: 0.0
decoder_layers:
  desc: null
  value: 12
decoder_start_token_id:
  desc: null
  value: 2
dropout:
  desc: null
  value: 0.1
early_stopping:
  desc: null
  value: true
encoder_attention_heads:
  desc: null
  value: 16
encoder_ffn_dim:
  desc: null
  value: 4096
encoder_layerdrop:
  desc: null
  value: 0.0
shared_encoder_layers:
  desc: null
  value: 11
encoder_heads:
  desc: null
  value: 1
eos_token_id:
  desc: null
  value: 2
forced_eos_token_id:
  desc: null
  value: 2
forced_bos_token_id:
  desc: null
  value: 0
gradient_checkpointing:
  desc: null
  value: false
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
    '2': LABEL_2
init_std:
  desc: null
  value: 0.02
is_encoder_decoder:
  desc: null
  value: true
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
    LABEL_2: 2
max_position_embeddings:
  desc: null
  value: 1024
model_type:
  desc: null
  value: bart
no_repeat_ngram_size:
  desc: null
  value: 3
normalize_before:
  desc: null
  value: false
num_beams:
  desc: null
  value: 4
num_hidden_layers:
  desc: null
  value: 12
pad_token_id:
  desc: null
  value: 1
scale_embedding:
  desc: null
  value: false
task_specific_params:
  desc: null
  value:
    summarization:
      length_penalty: 1.0
      max_length: 128
      min_length: 12
      num_beams: 4
    summarization_cnn:
      length_penalty: 2.0
      max_length: 142
      min_length: 56
      num_beams: 4
    summarization_xsum:
      length_penalty: 1.0
      max_length: 62
      min_length: 11
      num_beams: 6
transformers_version:
  desc: null
  value: 4.30.2
use_cache:
  desc: null
  value: true
vocab_size:
  desc: null
  value: 50265
_wandb:
  desc: null
  value:
    python_version: 3.9.11
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701417232.198974
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 100
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 100
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.9.11
      5: 0.15.4
      6: 4.30.2
      8:
      - 5
    m:
    - 1: train/global_step
      6:
      - 3
encoder_layers:
  desc: null
  value: 12
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: null
use_bfloat16:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: true
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
max_length:
  desc: null
  value: 20
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
chunk_size_feed_forward:
  desc: null
  value: 0
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
finetuning_task:
  desc: null
  value: null
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
sep_token_id:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: /Users/clementgillet/Desktop/Master_Hub/ebart.large/model.bin
output_dir:
  desc: null
  value: /Users/clementgillet/PycharmProjects/E-BART/e_bart/output
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: steps
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 4
per_device_eval_batch_size:
  desc: null
  value: 4
per_gpu_train_batch_size:
  desc: null
  value: None
per_gpu_eval_batch_size:
  desc: null
  value: None
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: None
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 3.0e-05
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 5.0
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: linear
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: /Users/clementgillet/PycharmProjects/E-BART/e_bart/output/runs/Dec01_08-53-53_eduroam-141-23-191-149.wlan.tu-berlin.de
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: steps
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: None
save_safetensors:
  desc: null
  value: false
save_on_each_node:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: None
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: None
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: None
tpu_num_cores:
  desc: null
  value: None
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: '[]'
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 1000
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: /Users/clementgillet/PycharmProjects/E-BART/e_bart/output
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: None
load_best_model_at_end:
  desc: null
  value: true
metric_for_best_model:
  desc: null
  value: loss
greater_is_better:
  desc: null
  value: false
ignore_data_skip:
  desc: null
  value: false
sharded_ddp:
  desc: null
  value: '[]'
fsdp:
  desc: null
  value: '[]'
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value: '{''fsdp_min_num_params'': 0, ''xla'': False, ''xla_fsdp_grad_ckpt'': False}'
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: None
deepspeed:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: adamw_hf
optim_args:
  desc: null
  value: None
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value: '[''tensorboard'', ''wandb'']'
ddp_find_unused_parameters:
  desc: null
  value: None
ddp_bucket_cap_mb:
  desc: null
  value: None
dataloader_pin_memory:
  desc: null
  value: true
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: None
hub_model_id:
  desc: null
  value: None
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: None
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: None
torch_compile_mode:
  desc: null
  value: None
xpu_backend:
  desc: null
  value: None
sortish_sampler:
  desc: null
  value: false
predict_with_generate:
  desc: null
  value: true
generation_max_length:
  desc: null
  value: 250
generation_num_beams:
  desc: null
  value: None
generation_config:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 4
eval_batch_size:
  desc: null
  value: 4
